### ISSUE TITLE
GET-IT: Update GeoNode to 3.3.x

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/starterkit#29]
We need to migrate the project to GeoNode 3.0 (and Python 3)

Update the current OWS python lib (01-2020 OWSLib 0.19.1) to the last updated version (0.23.0)

**Comment by chpicone** [comment]
Please, @marthamareal can you take a look on it?

**Comment by afabiani** [comment]
@giohappy PR available [here](https://github.com/geosolutions-it/starterkit/pull/43)
