### ISSUE TITLE
GET-IT: add SOS service provider to remote services

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/starterkit#33]
@chpicone commented on [Thu May 06 2021](https://github.com/geosolutions-it/support/issues/1374)

We need to make the user able to add SOS service providers as Remote Services.

---

@chpicone commented on [Fri May 07 2021](https://github.com/geosolutions-it/support/issues/1374#issuecomment-834158691)

`20200508AF: l'analisi prevede l'integrazione e configurazione dei SOS dal pannello dei Remote Services. 
Questo richiede non solo l'improvement dei Remote Services, in particolare aggiunta del livello di A&A e pluggabilità delle interfacce in base al tipo di servizio, ma anche la creazione dei servizi SOS da integrare e relativi harvester`

`20200508AF: the analysis involves the integration and configuration of the SOS from the Remote Services panel. 
This requires not only the improvement of the Remote Services, in particular the addition of the A&A level and pluggability of the interfaces based on the type of service, but also the creation of the SOS services to be integrated and related harvesters`

**Comment by chpicone** [comment]
> 20200508AF: the analysis involves the integration and configuration of the SOS from the Remote Services panel. 
>This requires not only the improvement of the Remote Services, in particular the addition of the A&A level and pluggability of the interfaces based on the type of service, but also the creation of the SOS services to be integrated and related harvesters.

**Comment by chpicone** [comment]
@marthamareal [HERE](https://docs.google.com/drawings/d/1vc3BlVkeA0os7-_RL8M5VuWbu9tSLsJec1o2WTkG6cE/edit?usp=sharing) you can find a simple schema of the models extracted by the customer requirements.

**Comment by giohappy** [comment]
closed in favour of https://github.com/geosolutions-it/starterkit/issues/44
