### ISSUE TITLE
GET-IT installation with NAT

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/starterkit#4]
Original Issue on SP7-Ritmare/starterkit
https://github.com/SP7-Ritmare/starterkit/issues/178

Configuration different port check issue: after authentication on different port than 80 the admin app redirects to "localhost", in case of installation of GET-IT in local IP the admin app redirects to "localhost"

**Comment by afabiani** [comment]
Fixed by https://github.com/SP7-Ritmare/starterkit/pull/185
