### ISSUE TITLE
Analysis for the implementation of an external remote service module for SOS

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#44]
@minardimarcello as breifly discussed the idea, contrarely to what was [initially planned](https://github.com/geosolutions-it/starterkit/issues/33), is to:

 - investigate if we can implement a new remote service type outside of GeoNode, i.e. as a Django app / Python module to be placed inside the starterkit project
 - if we miss something (e.g. GeoNode's services module doesn't provide the ability to "install" custom service types) we must identify what would be required and the effort to implement the missing parts

We will plan the work on the base of the outcomes from this analysis.

A starting point for the analysy might be this (WIP) closed PR  https://github.com/geosolutions-it/geonode/pull/898

**Comment by giohappy** [comment]
@minardimarcello as from our call what we want to estimate the effort to extend GeoNode `services` module to let a third-partymodule:
  - register a new service type (e.g. `sos` in this case)
  - (and consequantly) make users able to register a new  `sos` from the [Add Remote Services page](https://development.demo.geonode.org/services/register/)
  - make GeoNode ask the third party module how to show (text and links) the service when they are enumerated in the [Remote Services page](https://development.demo.geonode.org/services/?limit=5)
  - the third-party module will provide the texts and the links to it's own service management page

The `sos` service management page will let the user to harvest (i.e. retrieve) the sensors for the specific service.
We want to re-use the most as poddible the harvesting jobs provided by GeoNode `services`, so we should also analyse if and how we they can be leveraged by the third-party module. 

@etj do you confirm what I've written above?

**Comment by minardimarcello** [comment]
Hi @giohappy , 
here what I've written until now about it.
https://docs.google.com/document/d/1og_KFIJbF0jlF8d117noXWQzR_3y1QVZzLeMTaYzJfY/edit?usp=sharing

I'm going to create a fork where I've done the first point in the "Analyse if and how leveraged by the third-party module".
