### ISSUE TITLE
[3.3.x] Create a "SOS Remote Service" plugin for GeoNode

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/starterkit#45]
Leveraging on the work done for [[Fixes #8422] Added pluggable service types](https://github.com/GeoNode/geonode/pull/8688) we need to create a `pluggable` remote service for `SOS`.

Let's use the following as template/example

`https://github.com/GeoNode/geonode/blob/3.3.x/geonode/services/serviceprocessors/arcgis.py`

and the following URLs as references for the `SOS GetCapabilities` and `SOS DescribeSensor` requests:

- `http://getit.lteritalia.it/observations/sos/kvp?service=SOS&request=GetCapabilities`
- `http://vesk.ve.ismar.cnr.it/observations/sos/kvp?service=SOS&request=GetCapabilities`
- `http://nextdata.get-it.it/observations/sos/kvp?service=SOS&request=GetCapabilities`

There are several Python libraries which might be worth to check in order to connect to the sensor services, other than `OWSLib`, i.e.:

- `https://pypi.org/project/sos4py/`

The following `WMS Remote Service` in `GeoNode`, as an instance, leverages on the `OWSLib` in order to fetch the WMS resources.

 - `https://github.com/GeoNode/geonode/blob/3.3.x/geonode/services/serviceprocessors/wms.py#L124`

**Comment by giohappy** [comment]
If you agree @afabiani I would create a it in a dedicated repo, to keep it separate from starterkit and make it resuable in other contexts.

**Comment by afabiani** [comment]
@giohappy let's put this on geonode contribs

**Comment by mattiagiupponi** [comment]
@giohappy @afabiani follows a small demo of the pluggable app. Is the first prototype, there are still some stuff to fix

![demo_sensors](https://user-images.githubusercontent.com/51856725/155499336-a55eb8fe-208d-4fd7-a50a-f12d08f19b5e.gif)
