### ISSUE TITLE
Create SOS extensions for GeoNode MapStore client

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#46]
The SOS client extension will be available for Maps (only).

It will provide the following functionality:

 - a generic SOS catalog component to query and filter the catalog of sensors exposed but the SOS module API. This extension will be shipped with the SOS module itself, which is a contrib module: https://github.com/GeoNode/geonode-contribs/tree/master/sos 
 - a viewer for the GFI results, that will perform additional calls to the SOS module and will render an iframe that will take care of managing the response data. This viewer has specific logic for starterkit, so it will be shipped inside this repo.

### SOS catalog
The SOS catalog component will work the same as the generic datasets catalog. 

 - It will send query requests to the [SOS sensors endpoint](https://github.com/GeoNode/geonode-contribs/issues/152#issuecomment-1078931421)
 - the main search input will filter by `name`
 - additional inputs will be available for filtering by SOS service and/or observable property. This part is still a wip so it will be implemented when the API is available.

The response will be the same as a dataset, including the WMS link to add the sensor layer to the map.

### iframe results viewer
When a user clicks on the map the usual GFI requests are performed. The GFI response will be available inside the identify panel, as usual, but for the SOS sensors layers a custom result viewer will we rendered. This viewer will perform the following sequence:

1. Query the [FOI detail endpoint](https://github.com/GeoNode/geonode-contribs/issues/152#issuecomment-1078931421) with the id obtained from the GFI result.
2. Render a preconfigured iframe page (which is served by the customer). How to obtain this configuration is yet to be decided, but read the "generic iframe result viewer" notes below.
3. Send the following JSON to the iframe in the form of a [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) 

```
{
    "payload": {json obtained from the response at point 1},
    "clickCoordinates": {the two WOS84 coordinates of the point the user clicked on the map}
}
```

This iframe results viewer will show a button to let the user expand the panel and/or open it in a new browser tab.

### Notes
the iframe viewer should be built on top of a generic iframe results viewer for GeoNode MapStore client. The generic version would do the following:

1. Render a preconfigured iframe page (which is served by the customer). The configuration could be provided inside the response of the datasets catalog, so that a different viewer could be configured for each layer. To be discussed.
2. Send the GFI response to the iframe in the form of a [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

**Comment by mattiagiupponi** [comment]
Here is the list of the endpoints available with the SOS library

Sensors:

```
Endpoint:
GET http://localhost:8000/api/v2/sos/sensors/
```

FILTERS (all filters work in icontains):
```
title:
http://localhost:8000/api/v2/sos/sensors?title={tilte}

sos_url:
http://localhost:8000/api/v2/sos/sensors?sos_url={sos_url}

name:
http://localhost:8000/api/v2/sos/sensors?name={name}
(this will be returned as sos_name in the API)

observable_property:
http://localhost:8000/api/v2/sos/sensors?observable_property=http://vocab.nerc.ac.uk/collection/P01/current/CPRRRG01/
```
FOI
```
Endpoint listing: 
GET http://localhost:8000/api/v2/sos/fois/

Endpoint Detail
GET http://localhost:8000/api/v2/sos/fois/{foi_id}
```

Filters

```
multiple ids:
GET http://localhost:8000/api/v2/sos/fois/
Payload: {"model_field_name": ["list_of_ids"]}
example:
{
    "pk": [1, 2, 3]
}
```

**Comment by giohappy** [comment]
@mattiagiupponi we also need two APIs returning the list of SOS and observable properties. 

A user will never know what a valid value will be available for those filters otherwise.

The endpoints should be filterable, so that SOS will be returned given a specific observable and viceversa.

**Comment by mattiagiupponi** [comment]
@giohappy @DavidQuartz 
The PR with the API is available here https://github.com/GeoNode/geonode-contribs/pull/169
Follows the updated list of the available API in the SOS library. It should cover all possibilities needed, please let me know if something more is required:


Here is the list of the endpoints available with the SOS library

### Sensors:

```
Endpoint:
GET http://localhost:8000/api/v2/sos/sensors/
```

FILTERS (all filters work in icontains):
```
title:
http://localhost:8000/api/v2/sos/sensors?title={tilte}

sos_url:
http://localhost:8000/api/v2/sos/sensors?sos_url={sos_url}

name:
http://localhost:8000/api/v2/sos/sensors?sensor_name={name}
(this will be returned as sos_name in the API)

observable_property:
http://localhost:8000/api/v2/sos/sensors?observable_property=http://vocab.nerc.ac.uk/collection/P01/current/CPRRRG01/
```
### FOI
```
Endpoint listing: 
GET http://localhost:8000/api/v2/sos/fois/

Endpoint Detail
GET http://localhost:8000/api/v2/sos/fois/{foi_id}
```

Filters

```
multiple ids filter in listing
GET http://localhost:8000/api/v2/sos/fois/
Payload: {"model_field_name": ["list_of_ids"]}
example:
{
    "pk": [1, 2, 3]
}
```

### SOS Services

```
Endpoint:
GET http://localhost:8000/api/v2/sos/sos_service/
```

FILTERS (all filters work in icontains):
```
title:
http://localhost:8000/api/v2/sos/sos_service?title={tilte}

sos_url:
http://localhost:8000/api/v2/sos/sos_service?sos_url={sos_url}

name:
http://localhost:8000/api/v2/sos/sos_service?sensor_name={name}
(this will be returned as sos_name in the API)

observable_property:
http://localhost:8000/api/v2/sos/sos_service?observable_property=http://vocab.nerc.ac.uk/collection/P01/current/CPRRRG01/
```

### Observable Property

```
Endpoint:
GET http://localhost:8000/api/v2/sos/observable_properties/
```

FILTERS (all filters work in icontains):
```
title:
http://localhost:8000/api/v2/sos/observable_properties?title={tilte}

sos_url:
http://localhost:8000/api/v2/sos/observable_properties?sos_url={sos_url}

name:
http://localhost:8000/api/v2/sos/observable_properties?sensor_name={name}
(this will be returned as sos_name in the API)

observable_property:
http://localhost:8000/api/v2/sos/observable_properties?observable_property=http://vocab.nerc.ac.uk/collection/P01/current/CPRRRG01/
```

**Comment by giohappy** [comment]
@mattiagiupponi some concerns:

1) the name and title filter for the `sos_service` endpoint will be performed at the same time, so I suppose they will be treated in OR. E.g.  `http://localhost:8000/api/v2/sos/sensors?sensor_title={tilte}&sensor_name={name}`
2) I don't understand the `obervable_property` filter for the `obervable_property` endpoint. I expect to filter observable properties by their labels (e.d. Air Temperature) but I don't see this option

**Comment by mattiagiupponi** [comment]
> 1. the name and title filter for the `sos_service` endpoint will be performed at the same time, so I suppose they will be treated in OR. E.g.  `http://localhost:8000/api/v2/sos/sensors?sensor_title={tilte}&sensor_name={name}`

Ok, so in that case, is more searching than a filtering action

> 2. I don't understand the `obervable_property` filter for the `obervable_property` endpoint. I expect to filter observable properties by their labels (e.d. Air Temperature) but I don't see this option

That's why all the endpoints (except the FOI one) share the same CustomFilter to perform the filtering. Of course, this can be improved, I'm going to create a particular filter for the `observable_properties`

**Comment by giohappy** [comment]
@mattiagiupponi take a look at the screenshots in this [document](https://docs.google.com/document/d/1x4LFE0RHfQcjW3o63EgCD37wUoHJl2pfROYuuSbA9mo/edit?usp=drivesdkwhere) I have barely started the description of the plugin. You will see that what we're proposing is the usual search box, that we have in the standard catalogue, plus two (typeahead dropdow) filters.

Put yourself in the shoots of a user and think what yoy would write in those inputs. In general they will be terms, not alphanumeric identifier :)

**Comment by mattiagiupponi** [comment]
@giohappy this should be closer to the one expected, let me know if something is not clear or I'm missing some point.

### SENSORS

```
Endpoint: /api/v2/sos/sensors
Method: GET
```

Query params accepted:

```
sos_url: url of the sos service
sensor_title: title of the sensor
sensor_name: name of the sensor
observable_property: uniqueID of the property
property_label: observable property label
```

Note: if sensor_title and sensor_name are provided in the same call, an OR operation is performed. All the other query params are performed in AND

Example:

`http://localhost:8000/api/v2/sos/sensors?sensor_title=FluoroProbe&sensor_name=917AirTemp`

Returns:

```JSON
{
    "links": {
        "next": null,
        "previous": null
    },
    "total": 2,
    "page": 1,
    "page_size": 10,
    "layers": [
        {
            "pk": 2,
            "title": "Moldaenke FluoroProbe sensor",
            "sensor_name": "http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/1286194C-A5DF-11DF-8ED7-1602DFD72095",
            "sosUrl": "http://getit.lteritalia.it/observations/sos",
            "offeringsIDs": [
                "offering:http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/1286194C-A5DF-11DF-8ED7-1602DFD72095/observations"
            ],
            "observablePropertiesIDs": [
                "http://www.opengis.net/def/property/OGC/0/PhenomenonTime",
                "http://vocabs.lter-europe.net/EnvThes/20166",
                "urn:ogc:def:property:OGC:1.0.30:chla_green_conc",
                "urn:ogc:def:property:OGC:1.0.30:chla_bluegreen_conc",
                "urn:ogc:def:property:OGC:1.0.30:chla_diato_conc",
                "urn:ogc:def:property:OGC:1.0.30:chla_crypto_conc",
                "http://vocabs.lter-europe.net/EnvThes/22313",
                "http://vocabs.lter-europe.net/EnvThes/21549",
                "urn:ogc:def:property:OGC:1.0.30:transmission",
                "http://vocab.nerc.ac.uk/collection/P02/current/HMSB/"
            ]
        },
        {
            "pk": 5,
            "title": "Air Temperature sensor of LTER Zöbelboden",
            "sensor_name": "http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/SI000049-917AirTemp",
            "sosUrl": "http://getit.lteritalia.it/observations/sos",
            "offeringsIDs": [
                "offering:http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/SI000049-917AirTemp/observations"
            ],
            "observablePropertiesIDs": [
                "http://www.opengis.net/def/property/OGC/0/PhenomenonTime",
                "http://vocabs.lter-europe.net/EnvThes/22035"
            ]
        }
    ]
}
```

### FOIs

Endpoint listing: 
GET http://localhost:8000/api/v2/sos/fois/

Endpoint Detail
GET [http://localhost:8000/api/v2/sos/fois/{foi_id](http://localhost:8000/api/v2/sos/fois/%7Bfoi_id)}
multiple ids filter in listing
GET http://localhost:8000/api/v2/sos/fois/
Payload: {"model_field_name": ["list_of_ids"]}
Example: {"pk": [1, 2, 3]}
Returns:
```JSON
{
    "links": {
        "next": "http://localhost:8000/api/v2/sos/fois?page=2",
        "previous": null
    },
    "total": 9539,
    "page": 1,
    "page_size": 10,
    "feature_of_interests": [
        {
            "id": 2,
            "identifier": null,
            "name": "Candia - Lake Candia - 05",
            "sosUrl": "http://getit.lteritalia.it/observations/sos",
            "codespace": "http://www.opengis.net/def/nil/OGC/0/unknown",
            "feature_type": "http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/SF_SamplingPoint",
            "sampled_feature": "http://getit.lteritalia.it/layers/geonode:69",
            "geom": {
                "type": "Point",
                "coordinates": [
                    45.3262,
                    7.90974
                ]
            },
            "procedure": {
                "id": 3,
                "offeringsIDs": [
                    "offering:http://www.get-it.it/sensors/getit.lteritalia.it/procedure/CampbellScientificInc/noModelDeclared/noSerialNumberDeclared/20170914050327762_790362/observations"
                ],
                "observablePropertiesIDs": [
                    "http://www.opengis.net/def/property/OGC/0/PhenomenonTime",
                    "http://vocab.nerc.ac.uk/collection/P02/current/CAPH/",
                    "http://vocab.nerc.ac.uk/collection/P01/current/CTMP1001/",
                    "http://vocab.nerc.ac.uk/collection/P01/current/ERWDSS01/",
                    "http://vocab.nerc.ac.uk/collection/P01/current/CREL1001/",
                    "http://vocab.nerc.ac.uk/collection/P02/current/CSLR/",
                    "http://vocab.nerc.ac.uk/collection/P01/current/CPRRRG01/",
                    "http://vocab.nerc.ac.uk/collection/P01/current/EWDRSD01/",
                    "http://vocab.nerc.ac.uk/collection/P07/current/CFSN0039/",
                    "http://vocab.nerc.ac.uk/collection/P01/current/EWSTEN01/"
                ]
            }
        }
    ]
}
```


### Services

```
Endpoint: /api/v2/sos/sos_service
Method: GET
```

Query params accepted:

```
sos_url: url of the sos service
sensor_title: title of the sensor
sensor_name: name of the sensor
observable_property: uniqueID of the property
property_label: observable property label
```

Note: if sensor_title and sensor_name are provided in the same call, an OR operation is performed. All the other query params are performed in AND
Returns:
```JSON
{
    "links": {
        "next": null,
        "previous": null
    },
    "total": 1,
    "page": 1,
    "page_size": 10,
    "services": [
        {
            "id": 1,
            "title": "SOS Sensor Observation Service - Access of observations",
            "online_resource": "http://getit.lteritalia.it/observations/sos"
        }
    ]
}
```

### Observable properties:

```
Endpoint: /api/v2/sos/sos_service
Method: GET
```

Query params accepted:

```
sos_url: url of the sos service
sensor_title: title of the sensor
sensor_name: name of the sensor
observable_property: uniqueID of the property
property_label: observable property label
```

Note: if sensor_title and sensor_name are provided in the same call, an OR operation is performed. All the other query params are performed in AND
Returns:

```JSON
{
    "links": {
        "next": "http://localhost:8000/api/v2/sos/observable_properties?page=2",
        "previous": null
    },
    "total": 26,
    "page": 1,
    "page_size": 10,
    "layers": [
        {
            "id": 1,
            "definition": "http://www.opengis.net/def/property/OGC/0/PhenomenonTime",
            "property_label": "phenomenonTime"
        }
    ]
}
```
