### ISSUE TITLE
iframe viewer and message post

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#53]
When a user clicks on the map the usual GFI requests are performed. The GFI response will be available inside the identify panel, as usual, but for the SOS sensors layers a custom result viewer will we rendered. This viewer will perform the following sequence:

1. Query the [FOI detail endpoint](https://github.com/GeoNode/geonode-contribs/issues/152#issuecomment-1078931421) with the id obtained from the GFI result.
2. Render a preconfigured iframe page (which is served by the customer). How to obtain this configuration is yet to be decided, but read the "generic iframe result viewer" notes below.
3. Send the following JSON to the iframe in the form of a [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) 

```
{
    "payload": {json obtained from the response at point 1},
    "clickCoordinates": {the two WOS84 coordinates of the point the user clicked on the map}
}
```

Nice to have plus: This iframe results viewer will show a button to let the user expand the panel and/or open it in a new browser tab.

**Comment by DavidQuartz** [comment]
@giohappy do we have a uri for the iframe source?

**Comment by giohappy** [comment]
@DavidQuartz we don't have the src yet. But w shouldn't care. We can use a test page an post to it.

**Comment by giohappy** [comment]
@DavidQuartz as agreed we're going to change the approach for the visualization of the results inside the iframe. 

The client has accepted the new solution:

- when a GFI response contains one or more non-empty responses for the sensor layers a resizable modal window will be shown. The modal window contains the iframe
- the plugin will query the FOIs backend and then send the postMessage to the iframe
- the window will stay open until the user doesn't close it
- any new GFI response for the sensor layers will be posted to the same iframe
- the iframe will never be reloaded. When the modal is closed and reopened the same iframe, with the same status will be shown (if possible)
- we are not going to employ the standard GFI response panel to show the iframe. The standard GFI response will show the results as they're returned by the WMS service, as for any other layer. The user will in case switch the identify tool off if he wants to only interact with sensor layers and view the custom iframe window
