### ISSUE TITLE
Sensors missing from the resource type filter

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#60]
Why @mattiagiupponi?

![image](https://user-images.githubusercontent.com/571129/171436331-8aaa24ae-b32f-4cf9-93c8-ce09b236f71f.png)

**Comment by mattiagiupponi** [comment]
Issue fixed. PR: https://github.com/GeoNode/geonode-contribs/pull/200 and https://github.com/GeoNode/geonode/pull/9472
![image](https://user-images.githubusercontent.com/51856725/172132417-c0588ac8-acca-4bb4-8e56-cb15a1d13371.png)
