### ISSUE TITLE
Show sensor title inside the list of available resource from a SOS service

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#61]
- Name and description fields must be removed
 - We want to show the Title of the sensor which must be retrieved from the DescribeSensor response. To avoid sending dozens of requests at the same time, the DescrbeSensor request should be done only for the paginated results (sensors).

![image](https://user-images.githubusercontent.com/571129/171436802-7109cbe0-a0a3-4621-8b3e-eff00833486f.png)

**Comment by mattiagiupponi** [comment]
fixed via https://github.com/GeoNode/geonode-contribs/pull/206
