### ISSUE TITLE
type_in=sos_sensor query filter is not working

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#63]
I expect this page request will the sensor resources: `/layers/?limit=5&offset=0&type__in=sos_sensor`.
The same for `/search/?type__in=sos_sensor&limit=5&offset=0`, which is needed for the menu listing the sensors.

Maybe related to #60?

**Comment by mattiagiupponi** [comment]
Is related to #60 and the search must be done by resource_type=sos_sensor instead of type.
https://github.com/geosolutions-it/starterkit/issues/60#issuecomment-1147237294
