### ISSUE TITLE
Add buttons inside sensor card

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/starterkit#80]
Sensor buttons must be restored inside the sensors list page.

The buttons are the following links:

- **Sensor details**: `<service URL>/sensors/sensor/ds?format=text/html&sensor_id=<sensor ID>` (e.g. http://getit.lteritalia.it/sensors/sensor/ds/?format=text/html&sensor_id=http%3A//sp7.irea.cnr.it/sensors/getit.lteritalia.it/procedure/CampbellScientificInc/noModelDeclared/noSerialNumberDeclared/20170914050327762_790362)
- **Upload observations**: `<service URL>/sensors/upload?procedureId=<sensor ID>` (e.g. http://getit.lteritalia.it/sensors/upload?procedureId=http://sp7.irea.cnr.it/sensors/getit.lteritalia.it/procedure/CampbellScientificInc/noModelDeclared/noSerialNumberDeclared/20170914050327762_790362)
- **Download SensorML**: `<service URL>/observations/sos/kvp?service=SOS&version=2.0.0&request=DescribeSensor&procedureDescriptionFormat=http://www.opengis.net/sensorML/1.0.1&procedure=<sensor ID>` (e.g. http://getit.lteritalia.it/observations/sos/kvp?service=SOS&version=2.0.0&request=DescribeSensor&procedure=http://sp7.irea.cnr.it/sensors/getit.lteritalia.it/procedure/CampbellScientificInc/noModelDeclared/noSerialNumberDeclared/20170914050327762_790362&procedureDescriptionFormat=http://www.opengis.net/sensorML/1.0.1)
- **Download observations**: `<service URL>/observations/service?service=SOS&version=2.0.0&request=GetObservation&MergeObservationsIntoDataArray=true&procedure=<sensor ID>` (e.g. http://getit.lteritalia.it/observations/service?service=SOS&version=2.0.0&request=GetObservation&MergeObservationsIntoDataArray=true&procedure=http://sp7.irea.cnr.it/sensors/getit.lteritalia.it/procedure/CampbellScientificInc/noModelDeclared/noSerialNumberDeclared/20170914050327762_790362)
- **Delete sensor**: `<service URL>/sensors/deletesensor?procedure=<sensor ID>` (e.g.http://getit.lteritalia.it/sensors/deletesensor?procedure=http://sp7.irea.cnr.it/sensors/getit.lteritalia.it/procedure/CampbellScientificInc/noModelDeclared/noSerialNumberDeclared/20170914050327762_790362)

`<service URL>` can be retrieved from `ServiceProvider->service->base_url`

**NOTE**: **Upload observations** and **Delete sensor** shouls only be exposed for sensors coming from the local SOS service. There's no direct way to tell if a Service is local or not. We can probably compare the `ServiceMetadata.provider_url` (which is metadata populated by the local starterkit instance) with the  `ServiceProvider->service->base_url` to say if the Service is local.

![image](https://user-images.githubusercontent.com/571129/196663004-ca8e83f2-b213-42a3-9c56-37ea45c7c842.png)

**Comment by ptagliolato** [comment]
About the last point my suggestion is to determine if a sensor is local by comparing its endpoint against the one acknowledged e.g. in the /whoami as the "endpoint_SOS_url".

**Comment by giohappy** [comment]
Well, it might me easier then I thought. We can reuse the [same reverse URLs as you were doing before](https://github.com/geosolutions-it/starterkit/blob/master/src/geosk/osk/templates/osk/osk_list.html#L112-L126).

Notice that the download URL is defined as the sensor ID. I know it's not the real final URl, since you translate it and perform a redirection., but we're going to stick with the approach you implemented. We will  port this buttons toolbar to the new template only.

**Comment by giohappy** [comment]
In the end the original toolbar has been ported to the sensor list and it looks like this:

![image](https://user-images.githubusercontent.com/571129/196715649-8caee848-54c0-4aa5-8720-f523216810dd.png)

**Comment by giohappy** [comment]
closed with https://github.com/geosolutions-it/starterkit/commit/80048595073f33763ecdb3e54701ee8e50076a02
